# Generated by Django 2.1.4 on 2018-12-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QID', models.CharField(max_length=70)),
                ('Body', models.TextField()),
                ('Unit', models.CharField(max_length=10)),
                ('Old', models.CharField(max_length=2)),
                ('Number', models.CharField(max_length=70)),
            ],
        ),
    ]
