# Generated by Django 2.1.4 on 2019-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Number',
            new_name='Answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Old',
        ),
        migrations.AddField(
            model_name='question',
            name='ChoiceA',
            field=models.CharField(default='wtxqqq', max_length=70),
        ),
        migrations.AddField(
            model_name='question',
            name='ChoiceB',
            field=models.CharField(default='wtxqqq', max_length=70),
        ),
        migrations.AddField(
            model_name='question',
            name='ChoiceC',
            field=models.CharField(default='wtxqqq', max_length=70),
        ),
        migrations.AddField(
            model_name='question',
            name='ChoiceD',
            field=models.CharField(default='wtxqqq', max_length=70),
        ),
        migrations.AddField(
            model_name='question',
            name='TimeStamp',
            field=models.IntegerField(default=0),
        ),
    ]
