# Generated by Django 2.1.4 on 2019-01-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0002_auto_20190103_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Type',
            field=models.CharField(default='wtxqqq', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer',
            field=models.CharField(default='wtxqqq', max_length=70),
        ),
        migrations.AlterField(
            model_name='question',
            name='QID',
            field=models.CharField(default='wtxqqq', max_length=70),
        ),
        migrations.AlterField(
            model_name='question',
            name='Unit',
            field=models.CharField(default='wtxqqq', max_length=10),
        ),
    ]
